# ================================================
# Alacritty Terminal Configuration
# ================================================

# Environment variables to set when starting Alacritty
[env]
# Set the TERM environment variable to identify this as an Alacritty terminal
# This helps programs detect terminal capabilities correctly
TERM = "alacritty"

# Font configuration
[font]
# Alternative font sizes (commented out)
# size = 18.0

# Current font size in points - controls overall text size in the terminal
size = 20.0

# Shell configuration (currently disabled)
# Uncomment this section to customize the shell that Alacritty launches
# [shell]
# program = "/bin/zsh"
# # The 2 commands after login are needed to automatically attach to an existing tmux session
# # If no session exists, a new one is created
# args = ["--login", "-c", "/opt/homebrew/bin/tmux attach || //opt/homebrew/bin/tmux"]

# Window appearance settings
[window]
# Window decorations - "buttonless" removes window buttons but keeps title bar
# Other options: "none" (no decorations), "transparent" (see-through title bar)
decorations = "buttonless"

# Window transparency/opacity settings (0.0 = fully transparent, 1.0 = fully opaque)
# opacity = 0.99  # Almost opaque
opacity = 0.9     # Current setting - slightly transparent
# opacity = 0.8   # More transparent
# opacity = 0.7   # Very transparent

# Normal font family and style configuration
[font.normal]
# Alternative font families (commented out for reference)
# family = "Hack Nerd Font"
# style = "Regular"
# family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"

# Current font configuration
family = "JetBrainsMono Nerd Font"  # Font family with programming ligatures and icons
style = "Light"                     # Font weight/style

# Bold font configuration (currently disabled)
# Uncomment to customize bold text appearance
# [font.bold]
# # family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
# style = "Bold"

# Italic font configuration (currently disabled)
# Uncomment to customize italic text appearance
# [font.italic]
# family = "CaskaydiaCove Nerd Font"
# # family = "MesloLGS Nerd Font Mono"
# style = "Italic"

# ================================================
# Custom Keyboard Bindings
# ================================================
# These bindings likely integrate with tmux or other terminal multiplexers
# The escape sequences (\u001B) send specific key combinations to the shell

# Command+A: Send ESC+m sequence (typically tmux prefix + command)
[[keyboard.bindings]]
chars = "\u001Bm"
key = "A"
mods = "Command"

# Command+Period: Send ESC+. sequence (commonly used for argument completion)
[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Command"

# Command+D: Send ESC+d sequence (often used for word deletion or tmux detach)
[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Command"

# Command+B: Send ESC+b sequence (commonly used for backward word navigation)
[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Command"

# Command+T: Send ESC+t sequence (often used for tmux or tab operations)
[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Command"

# Command+F: Send ESC+f sequence (commonly used for forward word navigation)
[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Command"

# Control+N: Send Ctrl+N sequence (typically for next line/command in history)
[[keyboard.bindings]]
chars = "\u000E"
key = "N"
mods = "Control"

# Control+Space: Toggle Vi mode for text selection and navigation
[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control"


# ================================================
# Window Layout and Spacing
# ================================================

# Internal padding around the terminal content
[window.padding]
x = 8  # Horizontal padding in pixels (left and right margins)
y = 8  # Vertical padding in pixels (top and bottom margins)

# ================================================
# Selection and Clipboard Behavior
# ================================================

[selection]
# Automatically copy selected text to system clipboard
# When true, selecting text will immediately copy it without needing Cmd+C
save_to_clipboard = true

# ================================================
# General Terminal Settings
# ================================================

[general]
# Enable live configuration reloading - changes to this file take effect immediately
# without restarting Alacritty
live_config_reload = true

# Official Alacritty configuration documentation
# https://alacritty.org/config-alacritty.html

# Import external theme/color configuration files
# Currently using Catppuccin Mocha theme for colors
import = ["/Users/pawan/.config/alacritty/catppuccin-mocha.toml"]

# ================================================
# Alternative Color Scheme: Gruvbox Dark (Disabled)
# ================================================
# This is an alternative color scheme that can be enabled by uncommenting
# Remove the import line above and uncomment this section to use Gruvbox colors

# # Colors (Gruvbox dark)
#
# # Default colors
# [colors.primary]
# # hard contrast background = = '#1d2021'
# background = '#282828'    # Main background color - warm dark gray
# # soft contrast background = = '#32302f'
# foreground = '#ebdbb2'    # Main text color - warm light beige
#
# # Normal colors (standard 8 colors)
# [colors.normal]
# black   = '#282828'    # Dark gray (matches background)
# red     = '#cc241d'    # Dark red
# green   = '#98971a'    # Dark green
# yellow  = '#d79921'    # Dark yellow/orange
# blue    = '#458588'    # Dark blue
# magenta = '#b16286'    # Dark purple/magenta
# cyan    = '#689d6a'    # Dark teal/cyan
# white   = '#a89984'    # Light gray
#
# # Bright colors (bold/highlighted versions of the 8 colors)
# [colors.bright]
# black   = '#928374'    # Medium gray
# red     = '#fb4934'    # Bright red
# green   = '#b8bb26'    # Bright green
# yellow  = '#fabd2f'    # Bright yellow
# blue    = '#83a598'    # Bright blue
# magenta = '#d3869b'    # Bright purple/magenta
# cyan    = '#8ec07c'    # Bright teal/cyan
# white   = '#ebdbb2'    # Warm white (matches foreground)
