# ================================================
# Alacritty Terminal Configuration
# ================================================

# Environment variables to set when starting Alacritty
[env]
# Set the TERM environment variable to identify this as an Alacritty terminal
# This helps programs detect terminal capabilities correctly
TERM = "alacritty"

# Font configuration
[font]
# Current font size in points - controls overall text size in the terminal
size = 20.0

# Window appearance settings
[window]
# Window decorations - "buttonless" removes window buttons but keeps title bar
# Other options: "none" (no decorations), "transparent" (see-through title bar)
decorations = "buttonless"

# Window transparency/opacity settings (0.0 = fully transparent, 1.0 = fully opaque)
opacity = 0.9     # Current setting - slightly transparent

# Normal font family and style configuration
[font.normal]
# Current font configuration
family = "JetBrainsMono Nerd Font"  # Font family with programming ligatures and icons
style = "Light"                     # Font weight/style

# ================================================
# Custom Keyboard Bindings
# ================================================
# These bindings likely integrate with tmux or other terminal multiplexers
# The escape sequences (\u001B) send specific key combinations to the shell

# Command+A: Send ESC+m sequence (typically tmux prefix + command)
[[keyboard.bindings]]
chars = "\u001Bm"
key = "A"
mods = "Command"

# Command+Period: Send ESC+. sequence (commonly used for argument completion)
[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Command"

# Command+D: Send ESC+d sequence (often used for word deletion or tmux detach)
[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Command"

# Command+B: Send ESC+b sequence (commonly used for backward word navigation)
[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Command"

# Command+T: Send ESC+t sequence (often used for tmux or tab operations)
[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Command"

# Command+F: Send ESC+f sequence (commonly used for forward word navigation)
[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Command"

# Control+N: Send Ctrl+N sequence (typically for next line/command in history)
[[keyboard.bindings]]
chars = "\u000E"
key = "N"
mods = "Control"

# Control+Space: Toggle Vi mode for text selection and navigation
[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control"


# ================================================
# Window Layout and Spacing
# ================================================

# Internal padding around the terminal content
[window.padding]
x = 8  # Horizontal padding in pixels (left and right margins)
y = 8  # Vertical padding in pixels (top and bottom margins)

# ================================================
# Selection and Clipboard Behavior
# ================================================

[selection]
# Automatically copy selected text to system clipboard
# When true, selecting text will immediately copy it without needing Cmd+C
save_to_clipboard = true

# ================================================
# General Terminal Settings
# ================================================

[general]
# Enable live configuration reloading - changes to this file take effect immediately
# without restarting Alacritty
live_config_reload = true

# Official Alacritty configuration documentation
# https://alacritty.org/config-alacritty.html

# Import external theme/color configuration files
# Currently using Catppuccin Mocha theme for colors
import = ["/Users/pawan/.config/alacritty/catppuccin-mocha.toml"]