# Don't start AeroSpace automatically on login
start-at-login = false

# Normalization rules to improve layout behavior
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Padding for accordion layout mode
accordion-padding = 40

# Default layout for new workspaces
default-root-container-layout = 'accordion'

# Automatic orientation based on container size
default-root-container-orientation = 'auto'

# Mouse follows focus behavior
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']




# Floating window rules for utility apps
[[on-window-detected]]
if.app-name-regex-substring = 'keycastr'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'mpv'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'shottr'
run = 'layout floating'

# Terminal applications → Workspace 2
[[on-window-detected]]
if.app-id = 'org.alacritty'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-name-regex-substring = 'ghostty'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'WezTerm'
run = 'move-node-to-workspace 2'

# Browser applications
[[on-window-detected]]
if.app-name-regex-substring = 'chrome'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-name-regex-substring = 'chromium'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-name-regex-substring = 'Brave'
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-name-regex-substring = 'firefox'
run = 'move-node-to-workspace 9'

# Communication apps
[[on-window-detected]]
if.app-name-regex-substring = 'whatsapp'
run = ['layout floating', 'move-node-to-workspace 6']

# Note-taking and productivity
[[on-window-detected]]
if.app-name-regex-substring = 'Obsidian'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'com.thenounproject.Noun-Project'
run = "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'cisco'
run = ['layout floating', 'move-node-to-workspace 5']

[[on-window-detected]]
if.app-name-regex-substring = 'teams'
run = ['layout floating', 'move-node-to-workspace 4']

[[on-window-detected]]
if.app-name-regex-substring = 'postman'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-name-regex-substring = 'slack'
run = ['layout floating', 'move-node-to-workspace 3']

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'outlook'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-name-regex-substring = 'viber'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'telegram'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'stremio'
run = 'layout floating'




[key-mapping]
preset = 'qwerty'

# Window gaps configuration
[gaps]
inner.horizontal = 8
inner.vertical =   6
outer.left =       2
outer.bottom =     1
outer.top =        2
outer.right =      2

[mode.main.binding]
cmd-shift-f = 'fullscreen'

cmd-slash = 'layout tiles horizontal vertical'
cmd-comma = 'layout accordion horizontal vertical'
# Window focus navigation (vim-like)
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Window movement
cmd-ctrl-h = 'move left'
cmd-ctrl-j = 'move down'
cmd-ctrl-k = 'move up'
cmd-ctrl-l = 'move right'

# Window resizing
cmd-ctrl-minus = 'resize smart -64'
cmd-ctrl-equal = 'resize smart +64'


# Workspace navigation
cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'

# Move windows to workspaces and follow focus
cmd-ctrl-1 = 'move-node-to-workspace 1 --focus-follows-window'
cmd-ctrl-2 = 'move-node-to-workspace 2 --focus-follows-window'
cmd-ctrl-3 = 'move-node-to-workspace 3 --focus-follows-window'
cmd-ctrl-4 = 'move-node-to-workspace 4 --focus-follows-window'
cmd-ctrl-5 = 'move-node-to-workspace 5 --focus-follows-window'
cmd-ctrl-6 = 'move-node-to-workspace 6 --focus-follows-window'
cmd-ctrl-7 = 'move-node-to-workspace 7 --focus-follows-window'
cmd-ctrl-8 = 'move-node-to-workspace 8 --focus-follows-window'
cmd-ctrl-9 = 'move-node-to-workspace 9 --focus-follows-window'

# Workspace utilities
alt-tab = 'workspace-back-and-forth'

# Enter service mode for advanced operations
cmd-ctrl-semicolon = 'mode service'

[workspace-to-monitor-force-assignment]
# Force workspace assignment to specific monitors
# Workspace 1 tries secondary monitor first, falls back to main
# All other workspaces prefer main monitor
1 = ['secondary', 'main']
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'
6 = 'main'
7 = 'main'
8 = 'main'
9 = 'main'
r = 'main'

# Service mode for advanced operations
[mode.service.binding]
esc = ['reload-config', 'mode main']          # Reload config and exit service mode
r = ['flatten-workspace-tree', 'mode main']   # Reset layout to default
f = ['layout floating tiling', 'mode main']   # Toggle between floating and tiling
backspace = ['close-all-windows-but-current', 'mode main']  # Close all except current

# Join windows with containers
alt-ctrl-l = ['join-with right', 'mode main']
